## Introduction

\pagenumbering{arabic}

The price elasticity of housing supply is a key parameter in urban economics because it drives the congestion externalities and governs urban growth dynamics. An inelastic supply of land or housing means that any positive change in housing demand or location due to a positive productivity or amenity shock translates into higher prices---a major source of urban disutility---rather than higher quantities. On the contrary, if housing is supplied more elastically, we might expect smaller price changes and larger adjustments in city sizes. Moreover, inelastic supply aggravates house price differences across regions, affecting inter-regional labor mobility, and may constrain housing affordability in cities and regions, particularly in the big and growing ones. Thus, the housing supply elasticity is central to understanding the long-term development of cities and regions [@combes_etal_2019; @glaeser_etal_2006; @saks_2008; @lerbs_2014].

Over the past two decades, house prices have risen in cities worldwide, often due to a combination of strong and growing demand and a limited supply of new housing. Significant variations in the level and growth of house prices across cities and locations within cities and regions have been recorded [@glaeser_2020; @hilber_mense_2021]. Undoubtedly, an unresponsive housing supply can lead to higher house prices. However, examining what limits the housing supply and why may take more work. For example, in the US, house price gaps in rural and urban areas are much larger than the gaps in construction costs which is understood as a reflection of the difficulty of building new houses, especially in dense urban cores [@glaeser_2020]. While building new houses may help reduce house prices and alleviate affordability issues, answering why some cities and regions can build more houses more flexibly than others in response to the growing demand for housing is essential. More precisely, why do changes in demand for housing, triggered by productivity or amenity shocks, increase house prices rather than inducing more construction activities and city growth in some cities and not others?

This study empirically examines these questions by analyzing the growth of housing supply and house prices between 2008-2019 across the 401 German districts.[^01-intro-1] More precisely, I estimate the price elasticity of housing supply from a productivity or amenity shock induced response in housing supply. The main source of variation exploited for identifying the housing supply elasticity parameter is a @bartik_1991 labor demand shock, which has been widely used in the literature (for example, @saiz_2010 and @baum-snow_han_2019) as a proxy for demand. As such, average housing supply elasticity estimates reflect variations in housing demand shocks due to changes in labor demand over time across districts.

[^01-intro-1]: There are 401 districts ("Kreise" in German) according to the 2019 end-of-the-year [(31.12.2019)](https://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/Gemeindeverzeichnis/Administrativ/Archiv/Verwaltungsgliederung/31122019_Jahr.html) administrative structure breakdown.

However, construction costs or productivity, existing land development, and land use regulations may also influence housing supply differences. These factors can also mediate the responsiveness of the housing supply to changes in housing demand. Evidently, housing supply variations across districts are high due to differences in existing development intensity and land availability constraints. Therefore, parameterizing the housing supply elasticity with these observed housing supply heterogeneities allows us to get elasticity estimates at the district level and captures the importance of these factors in mediating the relationship between housing quantity and price.

<!-- > *What makes this paper different?* -->

Much of the existing evidence on the housing supply elasticity comes from the US housing market, but the literature is limited for other countries due to data availability, particularly for Germany. To my knowledge, only @lerbs_2014 estimated the housing supply elasticity for Germany, using a dynamic panel data model from new construction permits of single-family homes for 2004-2010. By adopting the recent approaches in the literature [@saiz_2010; @hilber_vermeulen_2016; @baum-snow_han_2019], this paper presents the German housing market's peculiarities regarding the housing supply elasticity.[^01-intro-2] For doing so, I leverage a detailed unique house price data set by @@rwi_immobilienscout24_2020 covering the whole of Germany available for 2007 onward. Furthermore, in line with the housing production literature, I use total residential floorspace over housing units as the main measure of housing quantity as it better captures the true level of housing supply [@baum-snow_han_2019; @epple_etal_2010].[^01-intro-3]

[^01-intro-2]: The German housing market is known for its stability, pro-tenant rental laws, moderate rental income taxes, low interest rates, recent fundamental supply shortages, and stiff land use regulations ([German Property Market Outlook 2021, Deutsche Bank AG, accessed August 10, 2022](https://www.dbresearch.com/PROD/RPS_EN-PROD/PROD_0000000000517463/Outlook_for_the_German_residential_property_market.pdf?undefined&realload=OGCzKhorommVYqr3DKzCKCT/4~0T75BVVmGs5XHbQs3QdBI~xyjvWG3i2CAeU6MJ), [Global Property Guide, accessed August 12, 2022](https://www.globalpropertyguide.com/Europe/Germany)). Moreover, it was one of the few housing markets that experienced less house price volatility during the 2008-2009 financial crisis. Because of these unique features (subtle nuances), studying this market, particularly concerning housing supply and elasticity differences across districts, would be a great addition to the literature.

[^01-intro-3]: In the literature, housing supply has been measured or proxied by several variables, including housing units (stock), new construction permits, completions, and starts, and the number of households (e.g., @saiz_2010).

Using a reduced form approach, I recover the housing supply elasticity as the impact of housing demand-induced growth in house prices on residential floor space growth over 2008-2019. Following the housing production literature, I derive a housing supply function incorporating local variations in construction costs or productivity and land availability. This allows writing the housing supply elasticity as a function of the same factors. Finally, I estimate the housing supply elasticity via a two-stage least squares (2SLS) estimation using predicted employment growth as an instrument for house price growth.

The data show that most districts in Germany have experienced substantial growth in house prices, an about `r round(100 * (d1$p_2019/d1$p_2008 - 1))`% change between 2008 and 2019, on average. Urban districts, in particular, have experienced slightly higher growth than rural districts, but there is little difference in price growth between the West and East German districts. In contrast, the housing supply growth has been weak across German districts, about `r round(100 * (d1$h_2019/d1$h_2008 - 1))`%, on average. New construction permits and completions have been continuously declining since 1995, gradually rising after 2009, yet the 2008-2019 levels remain far below the late 1990s and early 2000s.

Consequently, districts, on average, have been supply-inelastic. According to the baseline results, on average, a district has about `r round2(eps.fs.1)` elasticity in floorspace, `r round2(eps.u.1)` in units. That means, over the 2008-2019 period, a 10% increase in house prices has generated a `r 10*round2(eps.fs.1)`% growth in residential floorspace, on average, keeping other things constant. These estimates are similar to what @lerbs_2014 found for 2004 to 2010 (a short-run elasticity of 0.25 and a long-run value of `r round2(0.25/(1-0.37))`).[^01-intro-4] @baum-snow_han_2019 also found housing supply elasticity estimates in a similar range for census tracts in the US for 2000-2010.[^01-intro-5]

[^01-intro-4]: Apart from the time periods, however, estimates in this paper may be different from @lerbs_2014 estimates due to differences in the empirical methods employed. First, permits are used as housing quantity measure, as opposed to residential floorspace used in this paper. Second, the price data used in the two papers are different.

[^01-intro-5]: The authors estimate the housing supply elasticity to be in a range of 0.3-0.5 aggregated to the Metropolitan Statistical Area (MSA) level (see (3) and (8) columns of Table 6 and Table 11 in the Appendix of their paper).

The baseline specification conceals district heterogeneity since it does not allow the housing supply elasticity to vary across districts. Instead, the main specifications allow housing supply elasticities to vary across districts as a function of housing supply constraints. This is achieved by interacting price growth with fractions of already developed land and land that cannot be developed because of steep slopes and water bodies. According to the results, only land development intensity significantly constrains the housing supply elasticity in German districts, while land undevelopability due to restrictive geography has no significant impact. Land development intensity lowers the housing supply elasticity by about `r round2(abs(est.fs.4$b_dev))`. Moving in the interquartile range of existing development intensity (`r paste(sprintf("%.1f%%", 100 * iqr$dev), collapse = ", ")`) reduces the floorspace elasticity by `r round2(abs(est.fs.4$b_dev * diff(iqr$dev)))`, from `r round3(est.fs.4$vareps + est.fs.4$b_dev * iqr$dev[1])` to `r round3(est.fs.4$vareps + est.fs.4$b_dev * iqr$dev[2])`.

Finally, this paper provides robust housing supply elasticity estimates for Germany from 2008-2019. These estimates may prove useful for calibrating quantitative urban or regional models in Germany, which previously relied heavily on estimates for other markets. In addition, the study's utilization of supply constraints in Germany, precisely the measurement of undevelopable land constructed from elevation and land cover data, can be valuable for other studies examining housing supply constraints in Germany.
