# Literature

<!-- > [*Prepare a table that summarizes the existing literature: indicate what housing supply measure used, time period, intervals of estimates, spatial scale, and so on*] -->

This study builds on a growing body of literature examining the determinants of housing supply. The existing literature presents strong evidence regarding the impact of supply constraints on house prices and the housing supply elasticity in the US housing markets [@glaeser-gyourko2005; @saiz2010; @paciorek2013; @baumsnow-han2019]. In other markets, the literature is somewhat limited, except for a few notable studies, such as @hilber-vermeulen2016 and @büchler2021, which looked at the UK and Swiss markets, respectively. Much of the existing work looks at differences between cities concerning spatial scale. Few studies take on within cities and regions, such as neighborhoods, at a much finer spatial scale, for example, @baumsnow-han2019.

@glaeser-gyourko2005, @saiz2010, @paciorek2013, @hilber-vermeulen2016, and @baumsnow-han2019 explore the relationship between housing prices and various factors such as regulatory approval, geography, and land availability. @glaeser-gyourko2005 argues that changes in house prices in the US appear to result from a changing regulatory regime that has made large-scale development increasingly difficult in expensive regions of the country. @saiz2010 uses a variation of the Alonso-Mills-Muth model to show that land-constrained metro areas should have more expensive housing and higher amenities or productivity. Most areas widely regarded as supply inelastic were found to be severely land-constrained by their geography, and highly regulated areas were found to be geographically constrained. @paciorek2013 focuses on the relationship between supply constraints and house price volatility and indicates that permit delays and marginal costs of new investment explain much of the observable differences in elasticity across markets. @hilber-vermeulen2016 finds regulatory constraints to be the causal impact of various long-run supply constraints on house prices in England. Finally, @baumsnow-han2019 provides a comprehensive characterization of housing supply elasticities for residential neighborhoods in 306 US metro areas and finds that distance from urban centers, initial development density, topography, and zoning regimes are among the most important determinants of local housing supply.

In summary, the literature on the impact of supply constraints on house prices and supply is extensive in the US but limited for other countries [@hilber-vermeulen2016]. There is strong evidence stressing that both geographical constraints [see @saiz2010; @paciorek2013] and regulatory constraints [see @glaeser-gyourko2005; @paciorek2013; @gyourko-etal2021; @glaeser2020] explain much of the rapid house price growth across cities and markets in the US, as well in the UK [@hilber-vermeulen2016]. In most of the US studies, Wharton Residential Land Use Regulatory Index (WRLURI 2006 or 2018) has been exclusively used as a measure of regulatory restrictiveness. In contrast, @hilber-vermeulen2016 used a data set that includes direct information on actual planning decisions to measure regulatory restrictiveness. Regarding geographic constraints, mainly the degree of land development and unavailability, measures constructed from digital elevation models and land cover classes have been used. In the literature, housing supply is measured by several variables, including housing units (stock), construction permits, completions or starts, and household size. The housing production literature [see @epple-etal2010; @combes-etal2021] suggests using housing services, which can be proxied by floorspace, as a better measure, as used in @baumsnow-han2019. @bartik1991 is widely used as a main source of variation for identifying the housing supply elasticity parameter.
