## Conclusion

While the existing literature presents strong evidence about the impact of housing supply constraints on house prices and housing supply elasticities in the US housing market, the literature needs to be more comprehensive about other markets. Therefore, this paper attempts to highlight the unique characteristics of the German housing market concerning housing supply constraints and elasticity.

According to the data, house prices grew by more than `r round(round2(100 * (d$p2019/d$p2008 - 1)) / round2(100 * (d$h2019/d$h2008 - 1)))` times higher than that of housing supply, `r round2(100 * (d$p2019/d$p2008 - 1))`%, `r round2(100 * (d$h2019/d$h2008 - 1))`%, respectively, in the 2008-2019 period. Although this period has seen a growth in new housing construction, the levels are far below those of the early 1990s. As this growth imbalance suggests, Germany's housing supply is quite inelastic. Moreover, housing supply constraints tend to lower the housing supply elasticity, consistent with the literature, despite the small variations of topological constraints across districts. More precisely, districts with less built-up, and more flat and developable land, have a less inelastic housing supply. Land use regulations are also an important component of supply constraints, and their strong negative impact on housing supply and elasticity is well documented (see @glaeser_gyourko_2005, @saiz_2010, @baum-snow_han_2019). However, this paper's supply constraints are limited to topographical constraints due to the need for administrative land use regulation data. Future research could help us understand the stringency of land use regulation in Germany and its impact on house prices and housing supply.
